default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: raspbian_sources_select_development

test:
  <<: *default
  database: raspbian_sources_select_test

production:
  <<: *default
  database: raspbian_sources_select_production
